### ISSUE TITLE
It is impossible to un-name a plugin with rio-setup

### ISSUE THREAD

**Issue by itain** [multigcs/riocore#21]
If I give some item a name and then try to undo it, it is kept with an empty name.
Having multiple empty names will usually fail to halcompile the generated rio.c file.

Possibly best solution would be to ignore empty names in rio-generate.

**Comment by multigcs** [comment]
Thanks !
https://github.com/multigcs/riocore/commit/0eb0ecbe808fd9862b30a0a5e30203467c2eac96
