### ISSUE TITLE
rio-setup [UI] - modbus signals - display checkbox

### ISSUE THREAD

**Issue by itain** [multigcs/riocore#22]
I check items for display and add parameters.
Items are added to pyvcp as requested, but when I reopen the signals dialog the checkboxes are all unchecked.
Re-checking an item shows the saved parameters.

I'm not sure if there is a way to remove a display section.

**Comment by multigcs** [comment]
one could argue about whether that is what is wanted :)

the checkbox is actually a kind of work-around to have an expandable area

**Comment by multigcs** [comment]
sorry, to remove a displayed widget, you can set the Type to 'none'
