### ISSUE TITLE
Compatibility Inquiry: ALTERA Cyclone II FPGA with LinuxCNC-RIO

### ISSUE THREAD

**Issue by Tpj-root** [multigcs/riocore#24]
Sir,
I have an ALTERA FPGA Cyclone II EP2C5T144 board. Is it possible to use this with LinuxCNC-RIO for real-time I/O? If yes, could you provide any guidance or steps to make it work?

Thanks!

**Comment by multigcs** [comment]
not shure, 
the problem is that ‘Cyclone II’ is no longer supported by quartus and i don't know if rio works with the old version.

**Comment by multigcs** [comment]
in this zip-file i have a test gateware with makefile,
if this runs with the old quartus than we can add support for this fpga:
http://multixmedia.org/EP2C5T144.zip

**Comment by multigcs** [comment]
ok, i installed this version: 
https://www.intel.com/content/www/us/en/software-kit/711790/intel-quartus-ii-web-edition-design-software-version-13-0sp1-for-linux.html

and by removing some lines from pins.qdf (..IO_STANDARD..) i can build the bitfile.

so it looks good, but i can not test it.

**Comment by multigcs** [comment]
Ok, i have add support for this board :)

https://github.com/multigcs/riocore/commit/afc4bd855d440148068b1e432f1e019f482381ae
https://github.com/multigcs/riocore/commit/2849eedc1c1d7464477d58fa2bb9e2861c62d59e

but please tell me if it realy works, the demo config is only for blinking the LED

riocore/configs/EP2C5T144/config.json

**Comment by Tpj-root** [comment]
Sir, thank you for the immediate response. Please give me a few days. The board is available in the hackerspace lab, and I have requested them to send it to me. After I receive the package, I will try to install it and report to you on how it works..

**Comment by Tpj-root** [comment]
![2](https://github.com/user-attachments/assets/192f29c2-ee13-49de-ba12-0c0cd7b2d0c2)
![faild](https://github.com/user-attachments/assets/d2ff0960-3f58-4daa-a597-511d1407b3ad)

Sir, I finally received my package today and successfully compiled it, but I encountered an error. How can I fix this?

**Comment by multigcs** [comment]
hi, the flash command depends a lot on your hardware, you have to see how it is normally loaded on the fpga, maybe try OpenFPGAloader

**Comment by Tpj-root** [comment]
Sir,

I uploaded the .pof file using my friend's Windows machine, and it was uploaded successfully.

![POF](https://github.com/user-attachments/assets/36415f73-2993-4f29-9e32-b8deeec436da)

After that, I tested it with an oscilloscope:

![CH1and2](https://github.com/user-attachments/assets/157afea8-e068-4618-9c69-59f2f83f1cd5)

- PIN 17: CH1 (clock)
- Push button on PIN 144: CH2 (I get a signal when pressed)

I think it’s working. Now, I am waiting for your response to confirm if it’s really working.

**Comment by multigcs** [comment]
is one of the LED's blinking (1Hz) ? then it's working 

next step is setup something for the host connection (SPI / W5500), and create some IO's like StepDir or PWM outputs.


to flash, you can also try 
```
cd Output/EP2C5T144/Gateware
make prog
```
this will use the 'quartus_pgm' command to load the bitstream

**Comment by Tpj-root** [comment]
sir, To test the LED blinking using a push button and a 1kΩ pull-up resistor.
![tesing_blinking](https://github.com/user-attachments/assets/b7143a1a-d9b6-48b8-a7eb-602bfc7d3603)

**Comment by multigcs** [comment]
the LED have to blink constantly with 1Hz after flashing, no SW / PullUp / ... needed.

**Comment by multigcs** [comment]
but not shure my test bitfile have the blinking LED part, you have to build and compile your own bitfile

riocore/configs/EP2C5T144/config.json

**Comment by multigcs** [comment]
after 'usermod' you have to logout and re-login your user.

what programmer do you have ?

**Comment by Tpj-root** [comment]
sir, I have an Altera USB Blaster.
![USB-Blaster-ALTERA-CPLDFPGA-Programmer-1](https://github.com/user-attachments/assets/e31fd186-31f5-45cd-929b-fe928806171c)

**Comment by multigcs** [comment]
hmm, ok, normaly it should work

**Comment by Tpj-root** [comment]
Sir, after using OpenFPGALoader to manually upload the .svf file, the changes are temporary. Now the LED is blinking. Could you please confirm if it worked?

![3](https://github.com/user-attachments/assets/eaba7eb3-b288-4102-876b-e85a86fc7513)
![2](https://github.com/user-attachments/assets/03b5d820-aedf-4740-b01d-21fcef48a38c)

https://github.com/user-attachments/assets/5092d33b-e96f-4392-b03f-500fab72f58e

**Comment by multigcs** [comment]
looks very good :)
try to add '-f' option to your openFPGAloader command to write to flash

**Comment by Tpj-root** [comment]
Sir, The -f command does not work.
I think .sof and .svf files are not used for permanently programming the FPGA.
I need to use a file format that writes to non-volatile memory, such as .pof


.sof vs .pof
Both files show significant differences in their hex structure.

I believe the only way to permanently program the FPGA is by using the .pof file.
It seems to be the only solution.


Sir, I need your guidance.

I want to continue with this setup: LinuxCNC_RIO with the .svf file. After learning RIO and all the fundamentals (config, modules, and plugins), I will jump into RIOctrl FPGAs.

Can I continue? Or which path is perfect for learning the fundamentals?
Sir, Thank you for spending your precious time to answer my questions.

**Comment by multigcs** [comment]
what do you mean by RIOctrl FPGAs ?

**Comment by Tpj-root** [comment]
Sir, after that, I became familiar with RioCore. Is RIOctrl FPGAs suitable for advanced-level work in making CNC machines?

**Comment by multigcs** [comment]
you mean this board !?!?
https://github.com/festlv/rioctrl-hw

as far as i know, the basic parts are already working, but it's still in the test phase
