### ISSUE TITLE
Limit Variable Fields to Max 54 

### ISSUE THREAD

**Issue by xsnoopy** [multigcs/riocore#32]
I used a long description name in the GUI which ended up in an error starting LinuxCNC. Could you limit that? 

hal_pin_newfv: length 54 too long for name starting 'rio.Y_Axis_Joint_1_Left_with_Ball_screw.velocit'

**Comment by multigcs** [comment]
difficult, your string is 47 characters long
and is made up of different strings.

i will limit the text fields to 25 characters and hope that it is not too small for other things.

**Comment by multigcs** [comment]
https://github.com/multigcs/riocore/commit/1a655ac0f8d4fa3e61bb6abb3436ceb5bad0fde6
