### ISSUE TITLE
add support for this board Numato-Spartan6

### ISSUE THREAD

**Issue by Tpj-root** [multigcs/riocore#39]
Professor, I made some minor changes to the code in that PR.
PR [#38 ](https://github.com/multigcs/riocore/pull/38) created

![board](https://github.com/user-attachments/assets/1133c4ce-34e7-495c-9bbe-186cb3b61d77)
![HELP_1](https://github.com/user-attachments/assets/7f130356-9aca-45dc-946d-a5e0ba2722c4)
![HELP_2](https://github.com/user-attachments/assets/a6d54e23-13df-4b62-b67c-31fbd8b72f53)
[mygit](https://github.com/Tpj-root/FPGA_Spartan6)

Please verify my changes and add support for the Numato-Spartan-6 board.
Thank you for your time!

**Comment by multigcs** [comment]
thanks, is merged !
