### ISSUE TITLE
esp32 bridge alternative to w5500

### ISSUE THREAD

**Issue by jschoch** [multigcs/riocore#5]
perhaps UDP over USB is viable for bridge connection to LCNC host?

https://github.com/wezhunter/ESP32_LinuxCNC_MotionController_RealTime/issues/14

**Comment by wezhunter** [comment]
Yes it is and it will be! Nice spot! Even if its not used as a motion controller I reckon it will be a nice powerful low latency wireless accessory tool for LinuxCNC 😄

**Comment by wezhunter** [comment]
Sorry commented on the wrong repo. Darn github reference links. My bad. Must get sleep.

**Comment by multigcs** [comment]
@wezhunter 
haahaa, i was just confused too, i got an email from github with a text from your repo but with a link to mine 

```
Thanks for the PR.
Sorry for late reply. I've been hectic working on a big commit with lots of changes and bug fixes - including USB S2/S3 support.
Once that's complete it will be much smaller increments/fixes so contribution is easy. I'll definitely take a look at your PR soon

```

**Comment by multigcs** [comment]
@jschoch 
sounds good !

**Comment by jschoch** [comment]
closing this, it seems easier to just connect the esp32 directly to LCNC unless you need RT.
